"use client"
// import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";

const inter = Poppins({
  subsets: ["latin"],
  weight: "500"
});
const disableNavbar = ['/login', '/register']
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* auth-next */}
        <SessionProvider>
          {!disableNavbar.includes(pathname) && <Navbar />}
          {/* <Navbar></Navbar> */}
          {/* <div>This is Layout {state}</div>
        <button onClick={() => setState(state + 1)}>klik</button> */}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
